// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The payload of the `connection` event and command.
 */
export type Connection = { connected: boolean, socket: string, };
