// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One transcript entry.
 */
export type Entry = { "type": "update", update: import("@agentclientprotocol/sdk").SessionUpdate, } | { "type": "user_prompt", content: Array<import("@agentclientprotocol/sdk").ContentBlock>, };
