// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entry } from "./Entry";
import type { SessionSummary } from "./SessionSummary";
import type { Workspace } from "./Workspace";

export type Event = { "type": "terminal_exited", terminal: number, } | { "type": "watch_snapshot", workspaces: Array<Workspace>, sessions: Array<SessionSummary>, } | { "type": "workspace_added", workspace: Workspace, } | { "type": "workspace_removed", name: string, } | { "type": "session_changed", summary: SessionSummary, } | { "type": "session_snapshot", session: string, transcript: Array<Entry>, } | { "type": "entry", session: string, entry: Entry, } | { "type": "session_removed", session: string, };
