// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entry } from "./Entry";
import type { ServerState } from "./ServerState";
import type { SessionSummary } from "./SessionSummary";
import type { TerminalSummary } from "./TerminalSummary";
import type { Workspace } from "./Workspace";

export type Event = { "type": "terminal_exited", terminal: number, } | { "type": "watch_snapshot", workspaces: Array<Workspace>, sessions: Array<SessionSummary>, terminals: Array<TerminalSummary>, 
/**
 * The current ACP connection's capabilities, or `None` without one.
 */
capabilities: import("@agentclientprotocol/sdk").AgentCapabilities | null, server_state: ServerState, } | { "type": "server_state_changed", server_state: ServerState, } | { "type": "capabilities_changed", capabilities: import("@agentclientprotocol/sdk").AgentCapabilities, } | { "type": "workspace_added", workspace: Workspace, } | { "type": "workspace_removed", name: string, } | { "type": "session_changed", summary: SessionSummary, } | { "type": "terminal_changed", summary: TerminalSummary, } | { "type": "session_deleted", session: string, } | { "type": "session_snapshot", session: string, transcript: Array<Entry>, config_options: Array<import("@agentclientprotocol/sdk").SessionConfigOption>, } | { "type": "entry", session: string, entry: Entry, } | { "type": "config_options_changed", session: string, config_options: Array<import("@agentclientprotocol/sdk").SessionConfigOption>, } | { "type": "session_removed", session: string, };
