// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pending permission request.
 */
export type PendingPermission = { 
/**
 * Assigned by the daemon, counting from 1 across all sessions. The
 * JSON-RPC ID can be a string, a number, or null, and a `u32` keeps the
 * TypeScript binding `number`.
 */
request_id: number, request: import("@agentclientprotocol/sdk").RequestPermissionRequest, };
