// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Request = { "type": "open_terminal" } | { "type": "attach_terminal", terminal: number, rows: number, cols: number, } | { "type": "terminal_resize", terminal: number, rows: number, cols: number, };
