// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Response = { "type": "opened", terminal: number, } | { "type": "done" } | { "type": "error", message: string, };
