// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The session or terminal chosen in the sidebar.
 */
export type Selection = { "type": "terminal", terminal: number, } | { "type": "session", session: string, };
