// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The selected ACP server and the status of its connection.
 */
export type ServerState = { command: string | null, args: Array<string>, connected: boolean, error: string | null, };
