// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerIcon } from "./ServerIcon";

/**
 * One configured server and its current connection state.
 */
export type ServerState = { id: string, name: string, icon: ServerIcon, command: string, args: Array<string>, connected: boolean, error: string | null, capabilities: import("@agentclientprotocol/sdk").AgentCapabilities | null, };
