// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A server icon, which marks the server's sessions in the sidebar and their
 * tabs: the agent the server runs, in picker order.
 */
export type ServerIcon = "claude" | "codex" | "ox";
