// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

/**
 * One session as watch shows it.
 */
export type SessionSummary = { session: string, workspace: string, status: Status, unread: boolean, 
/**
 * The session title, from `session/list` or `session_info_update`.
 */
title: string | null, 
/**
 * The last activity, from `session/list` or `session_info_update`.
 */
updated_at: string | null, };
