// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable daemon reference to an ACP session owned by one configured server.
 */
export type SessionKey = string;
