// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

/**
 * One session as watch shows it.
 */
export type SessionSummary = { session: string, workspace: string, status: Status, unread: boolean, };
