// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingPermission } from "./PendingPermission";

/**
 * The session status.
 */
export type Status = { "type": "idle", last_stop: import("@agentclientprotocol/sdk").StopReason | null, } | { "type": "working" } | { "type": "needs_permission", requests: Array<PendingPermission>, } | { "type": "failed", message: string, };
