// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One terminal as watch shows it.
 */
export type TerminalSummary = { terminal: number, workspace: string, title: string, };
