// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceColor } from "./WorkspaceColor";

/**
 * A workspace, as the wire protocol and the state file hold it.
 */
export type Workspace = { name: string, path: string, color: WorkspaceColor, };
