[package]
name = "ur"
edition.workspace = true
version.workspace = true

[dependencies]
agent-client-protocol.workspace = true
anyhow.workspace = true
clap.workspace = true
futures.workspace = true
crossterm.workspace = true
unicode-width.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
ur-fake-server.workspace = true
