[package]
name = "ur"
edition.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
clap.workspace = true
futures.workspace = true
portable-pty.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
ur-client.workspace = true
vt100.workspace = true

[dev-dependencies]
tempfile.workspace = true
